GET http://localhost:3000/api/v1/

### Recuperar un contacto por nombre
GET http://localhost:3000/api/v1/jose

### Crea un nuevo contacto
POST http://localhost:3000/api/v1/
Content-Type: application/json

{
    "name": "Pepito Grillo",
    "birthday": "1986-05-12",
    "phone": 1234567890,
    "email": "fdsa@gmail.com"
}

### Borra un contacto y devuelve el contacto borrado
DELETE http://localhost:3000/api/v1/jose

### Actualiza un contacto y devuelve el contacto actualizado
PATCH http://localhost:3000/api/v1/maria
Content-Type: application/json

{
  "phone": 693177685
}